# CodeRabbit Configuration File
# Documentation: https://coderabbit.ai/docs/configure-coderabbit

language: "en-US"
early_access: false

reviews:
  profile: "assertive" # 'assertive' is better for strict security checking than 'chill'
  request_changes_workflow: false
  high_level_summary: true
  
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "wip"
      - "draft"
    drafts: false

  # Tools configuration
  tools:
    ast-grep:
      enabled: true
    # Enable other static analysis tools based on language
    eslint:
      enabled: true
    trivy: 
      enabled: true # Container/Dependency security scanner

  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/coverage/**"
    - "!**/*.lock"

chat:
  auto_reply: true

# Custom instructions for the AI to focus on vulnerabilities
instructions: |
  Please review the code with a strong focus on SECURITY and VULNERABILITIES.
  
  Specifically check for:
  1. SQL Injection (especially in Supabase queries if raw strings are used).
  2. XSS (Cross-Site Scripting) - unlikely in React but check for dangerouslySetInnerHTML.
  3. Exposure of Sensitive Information (API keys, secrets committed to code).
  4. Authentication/Authorization flaws (missing RLS policies, weak checks).
  5. Improper input validation.
  
  If you find any security issues, please flag them with high priority.
